apiVersion: aiven.nais.io/v1
kind: AivenApplication
metadata:
  name: sykepengevedtak-infotrygd-goldengate
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  kafka:
    pool: nav-dev
  secretName: sykepengevedtak-infotrygd-goldengate
  protected: true