apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: sykepengevedtak-infotrygd
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 2016
  acl:
    - team: teamfamilie
      application: familie-ef-vedtakhendelse
      access: read
    - team: teamfamilie
      application: sykepengevedtak-infotrygd-goldengate
      access: write