apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-ensligforsorger-eksterne-vedtak
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720
  acl:
    - team: teamfamilie
      application: familie-ef-vedtakhendelse
      access: readwrite
    - team: teamfamilie
      application: familie-ef-personhendelse
      access: read