apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-vedtakhendelse
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  ingresses:
    - https://familie-ef-vedtakhendelse.intern.dev.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      memory: 768Mi
    requests:
      memory: 512Mi
      cpu: 20m
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: familie-ef-sak
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        tier: db-g1-small
        cascadingDelete: false
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: familie-ef-vedtakhendelse
            envVarPrefix: DB
