name: Deploy kafka topics

on:
  workflow_dispatch:

permissions:
  contents: "read"
  id-token: "write"
  packages: "write"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: deploy privat-ensligforsorger-eksterne-vedtak to dev
        uses: nais/deploy/actions/deploy@e79279e20795c1a03a92e8ae0bad4b770fd4e6d4 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: kafka-aiven/eksterne-vedtak/topic-eksterne-vedtak-dev.yaml
          PRINT_PAYLOAD: true
      - name: deploy privat-ensligforsorger-eksterne-vedtak to prod
        uses: nais/deploy/actions/deploy@e79279e20795c1a03a92e8ae0bad4b770fd4e6d4 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: kafka-aiven/eksterne-vedtak/topic-eksterne-vedtak-prod.yaml
          PRINT_PAYLOAD: true
      - name: deploy sykepengevedtak-infotrygd to dev
        uses: nais/deploy/actions/deploy@e79279e20795c1a03a92e8ae0bad4b770fd4e6d4 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: kafka-aiven/sykepengevedtak-infotrygd/topic-sykepenger-infotrygd-dev.yaml
          PRINT_PAYLOAD: true
      - name: deploy sykepengevedtak-infotrygd to prod
        uses: nais/deploy/actions/deploy@e79279e20795c1a03a92e8ae0bad4b770fd4e6d4 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: kafka-aiven/sykepengevedtak-infotrygd/topic-sykepenger-infotrygd-prod.yaml
          PRINT_PAYLOAD: true
      - name: deploy aivenapp-sykepenger-infotrygd-goldengate to dev
        uses: nais/deploy/actions/deploy@e79279e20795c1a03a92e8ae0bad4b770fd4e6d4 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: kafka-aiven/sykepengevedtak-infotrygd/aivenapp-sykepenger-infotrygd-goldengate-dev.yaml
          PRINT_PAYLOAD: true
      - name: deploy aivenapp-sykepenger-infotrygd-goldengate to prod
        uses: nais/deploy/actions/deploy@e79279e20795c1a03a92e8ae0bad4b770fd4e6d4 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: kafka-aiven/sykepengevedtak-infotrygd/aivenapp-sykepenger-infotrygd-goldengate-prod.yaml
          PRINT_PAYLOAD: true
